import { motion } from 'motion/react'
import { ArrowRight, Phone, Mail, MapPin } from 'lucide-react'
import { useState } from 'react'

export default function Contact() {
  const [sent, setSent] = useState(false)
  const submit = (event) => { event.preventDefault(); setSent(true); event.currentTarget.reset() }
  return <section id="contact" className="bg-[#171717] py-24 text-white sm:py-28"><div className="mx-auto grid max-w-7xl gap-14 px-5 sm:px-8 lg:grid-cols-[.9fr_1.1fr] lg:gap-24 lg:px-10"><div><p className="mb-5 text-xs font-semibold uppercase tracking-[.22em] text-red-300">Start here</p><h2 className="max-w-lg text-4xl font-semibold leading-tight tracking-[-.04em] sm:text-5xl">Your next language is closer than you think.</h2><p className="mt-6 max-w-md leading-7 text-neutral-400">Tell us what you want to learn. We’ll help you choose the right course and format.</p><div className="mt-10 space-y-5 text-sm"><a href="tel:+998901234567" className="flex items-center gap-4 text-neutral-300 transition hover:text-white"><Phone size={18} className="text-red-300" /> +998 90 123 45 67</a><a href="mailto:info@hongkongacademy.uz" className="flex items-center gap-4 text-neutral-300 transition hover:text-white"><Mail size={18} className="text-red-300" /> info@hongkongacademy.uz</a><div className="flex items-center gap-4 text-neutral-300"><MapPin size={18} className="text-red-300" /> Tashkent, Uzbekistan</div></div></div><motion.form initial={{ opacity: 0, y: 15 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} onSubmit={submit} className="rounded-3xl bg-white p-6 text-neutral-900 sm:p-8"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium">Your name<input required name="name" placeholder="Name" className="mt-2 w-full rounded-xl border border-neutral-200 px-4 py-3 text-sm outline-none transition placeholder:text-neutral-400 focus:border-[#c40011]" /></label><label className="text-sm font-medium">Phone number<input required name="phone" type="tel" placeholder="+998" className="mt-2 w-full rounded-xl border border-neutral-200 px-4 py-3 text-sm outline-none transition placeholder:text-neutral-400 focus:border-[#c40011]" /></label></div><label className="mt-5 block text-sm font-medium">What would you like to learn?<textarea required name="message" rows="4" placeholder="Tell us about your goals..." className="mt-2 w-full resize-none rounded-xl border border-neutral-200 px-4 py-3 text-sm outline-none transition placeholder:text-neutral-400 focus:border-[#c40011]" /></label><button type="submit" className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-[#c40011] px-5 py-3.5 text-sm font-semibold text-white transition hover:bg-[#a9000f]">{sent ? 'Thank you — we’ll be in touch' : 'Send an enquiry'} {!sent && <ArrowRight size={17} />}</button></motion.form></div></section>
}
