import { motion } from 'motion/react'
import { ArrowUpRight } from 'lucide-react'
import { FaInstagram, FaTelegramPlane } from 'react-icons/fa'

const social = [{ name: 'Instagram', handle: '@hongkongacademy', text: 'See what is happening in our classrooms.', icon: FaInstagram, href: 'https://instagram.com' }, { name: 'Telegram', handle: 'Hong Kong Academy', text: 'Get news, tips, and course updates first.', icon: FaTelegramPlane, href: 'https://telegram.org' }]

export default function SocialMedia() {
  return <section className="bg-white py-24 sm:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="mb-12 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-4 text-xs font-semibold uppercase tracking-[.22em] text-[#c40011]">Stay connected</p><h2 className="text-4xl font-semibold tracking-[-.04em] text-neutral-950 sm:text-5xl">Keep the conversation going.</h2></div><p className="max-w-xs text-sm leading-6 text-neutral-500">A little inspiration for your language journey, every day.</p></div><div className="grid gap-4 md:grid-cols-2">{social.map((item, index) => { const Icon = item.icon; return <motion.a key={item.name} href={item.href} target="_blank" rel="noreferrer" initial={{ opacity: 0, y: 15 }} whileInView={{ opacity: 1, y: 0 }} transition={{ delay: index * .1 }} viewport={{ once: true }} className="group flex items-center justify-between rounded-3xl border border-neutral-200 bg-[#f8f8f6] p-6 transition hover:-translate-y-1 hover:border-red-100 hover:bg-white hover:shadow-xl sm:p-8"><div className="flex items-center gap-5"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-white text-[#c40011] shadow-sm transition group-hover:bg-[#c40011] group-hover:text-white"><Icon size={24} /></div><div><h3 className="text-lg font-semibold text-neutral-900">{item.name}</h3><p className="mt-1 text-sm text-[#c40011]">{item.handle}</p><p className="mt-2 hidden text-sm text-neutral-500 sm:block">{item.text}</p></div></div><ArrowUpRight size={20} className="text-neutral-300 transition group-hover:-translate-y-1 group-hover:translate-x-1 group-hover:text-[#c40011]" /></motion.a> })}</div></div></section>
}
